// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSBuTN4tIg8TBXFVPOHHodgrjLtJAPz7s',
    appId: '1:1001546573311:web:795fdf8e83d2cef829f3ca',
    messagingSenderId: '1001546573311',
    projectId: 'task-7afd0',
    authDomain: 'task-7afd0.firebaseapp.com',
    storageBucket: 'task-7afd0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtvJ2DOYqMer7oVZr6DRNFfAgwPoU7kXY',
    appId: '1:1001546573311:android:b1fcca067ca94de829f3ca',
    messagingSenderId: '1001546573311',
    projectId: 'task-7afd0',
    storageBucket: 'task-7afd0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-HZaxAFCmRaeJNr7VVWcLL5qwK3lVcYA',
    appId: '1:1001546573311:ios:949fc75c5d0fd98229f3ca',
    messagingSenderId: '1001546573311',
    projectId: 'task-7afd0',
    storageBucket: 'task-7afd0.appspot.com',
    iosBundleId: 'com.example.flutterFirabase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-HZaxAFCmRaeJNr7VVWcLL5qwK3lVcYA',
    appId: '1:1001546573311:ios:949fc75c5d0fd98229f3ca',
    messagingSenderId: '1001546573311',
    projectId: 'task-7afd0',
    storageBucket: 'task-7afd0.appspot.com',
    iosBundleId: 'com.example.flutterFirabase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSBuTN4tIg8TBXFVPOHHodgrjLtJAPz7s',
    appId: '1:1001546573311:web:e30129d1bfb4b33f29f3ca',
    messagingSenderId: '1001546573311',
    projectId: 'task-7afd0',
    authDomain: 'task-7afd0.firebaseapp.com',
    storageBucket: 'task-7afd0.appspot.com',
  );
}
